# Generated by Django 3.1.14 on 2022-01-28 21:50

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0022_dynamicgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicgroup',
            name='_members_cache',
            field=models.JSONField(blank=True, default=list, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='dynamicgroup',
            name='_members_count',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.CreateModel(
            name='DynamicGroupAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_assignments', to='contenttypes.contenttype')),
                ('dynamic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_assignments', to='extras.dynamicgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
